// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAllocationItems(t *testing.T) {
	t.Parallel()

	query := AllocationItems()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAllocationItemsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AllocationItem{}
	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AllocationItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAllocationItemsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AllocationItem{}
	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := AllocationItems().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AllocationItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAllocationItemsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AllocationItem{}
	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AllocationItemSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AllocationItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAllocationItemsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AllocationItem{}
	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AllocationItemExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if AllocationItem exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AllocationItemExists to return true, but got false.")
	}
}

func testAllocationItemsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AllocationItem{}
	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	allocationItemFound, err := FindAllocationItem(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if allocationItemFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAllocationItemsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AllocationItem{}
	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = AllocationItems().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAllocationItemsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AllocationItem{}
	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := AllocationItems().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAllocationItemsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	allocationItemOne := &AllocationItem{}
	allocationItemTwo := &AllocationItem{}
	if err = randomize.Struct(seed, allocationItemOne, allocationItemDBTypes, false, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}
	if err = randomize.Struct(seed, allocationItemTwo, allocationItemDBTypes, false, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = allocationItemOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = allocationItemTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AllocationItems().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAllocationItemsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	allocationItemOne := &AllocationItem{}
	allocationItemTwo := &AllocationItem{}
	if err = randomize.Struct(seed, allocationItemOne, allocationItemDBTypes, false, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}
	if err = randomize.Struct(seed, allocationItemTwo, allocationItemDBTypes, false, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = allocationItemOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = allocationItemTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AllocationItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func allocationItemBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *AllocationItem) error {
	*o = AllocationItem{}
	return nil
}

func allocationItemAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *AllocationItem) error {
	*o = AllocationItem{}
	return nil
}

func allocationItemAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *AllocationItem) error {
	*o = AllocationItem{}
	return nil
}

func allocationItemBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AllocationItem) error {
	*o = AllocationItem{}
	return nil
}

func allocationItemAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AllocationItem) error {
	*o = AllocationItem{}
	return nil
}

func allocationItemBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AllocationItem) error {
	*o = AllocationItem{}
	return nil
}

func allocationItemAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AllocationItem) error {
	*o = AllocationItem{}
	return nil
}

func allocationItemBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AllocationItem) error {
	*o = AllocationItem{}
	return nil
}

func allocationItemAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AllocationItem) error {
	*o = AllocationItem{}
	return nil
}

func testAllocationItemsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &AllocationItem{}
	o := &AllocationItem{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, allocationItemDBTypes, false); err != nil {
		t.Errorf("Unable to randomize AllocationItem object: %s", err)
	}

	AddAllocationItemHook(boil.BeforeInsertHook, allocationItemBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	allocationItemBeforeInsertHooks = []AllocationItemHook{}

	AddAllocationItemHook(boil.AfterInsertHook, allocationItemAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	allocationItemAfterInsertHooks = []AllocationItemHook{}

	AddAllocationItemHook(boil.AfterSelectHook, allocationItemAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	allocationItemAfterSelectHooks = []AllocationItemHook{}

	AddAllocationItemHook(boil.BeforeUpdateHook, allocationItemBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	allocationItemBeforeUpdateHooks = []AllocationItemHook{}

	AddAllocationItemHook(boil.AfterUpdateHook, allocationItemAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	allocationItemAfterUpdateHooks = []AllocationItemHook{}

	AddAllocationItemHook(boil.BeforeDeleteHook, allocationItemBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	allocationItemBeforeDeleteHooks = []AllocationItemHook{}

	AddAllocationItemHook(boil.AfterDeleteHook, allocationItemAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	allocationItemAfterDeleteHooks = []AllocationItemHook{}

	AddAllocationItemHook(boil.BeforeUpsertHook, allocationItemBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	allocationItemBeforeUpsertHooks = []AllocationItemHook{}

	AddAllocationItemHook(boil.AfterUpsertHook, allocationItemAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	allocationItemAfterUpsertHooks = []AllocationItemHook{}
}

func testAllocationItemsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AllocationItem{}
	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AllocationItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAllocationItemsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AllocationItem{}
	if err = randomize.Struct(seed, o, allocationItemDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(allocationItemColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := AllocationItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAllocationItemToOneAllocationUsingAllocation(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AllocationItem
	var foreign Allocation

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, allocationItemDBTypes, false, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, allocationDBTypes, false, allocationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Allocation struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.AllocationID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Allocation().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := AllocationItemSlice{&local}
	if err = local.L.LoadAllocation(ctx, tx, false, (*[]*AllocationItem)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Allocation == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Allocation = nil
	if err = local.L.LoadAllocation(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Allocation == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testAllocationItemToOneItemUsingItem(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AllocationItem
	var foreign Item

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, allocationItemDBTypes, false, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, itemDBTypes, false, itemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Item struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.ItemID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Item().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := AllocationItemSlice{&local}
	if err = local.L.LoadItem(ctx, tx, false, (*[]*AllocationItem)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Item == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Item = nil
	if err = local.L.LoadItem(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Item == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testAllocationItemToOneUnitUsingUnit(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AllocationItem
	var foreign Unit

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, allocationItemDBTypes, false, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, unitDBTypes, false, unitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Unit struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UnitID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Unit().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := AllocationItemSlice{&local}
	if err = local.L.LoadUnit(ctx, tx, false, (*[]*AllocationItem)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Unit == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Unit = nil
	if err = local.L.LoadUnit(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Unit == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testAllocationItemToOneSetOpAllocationUsingAllocation(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AllocationItem
	var b, c Allocation

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, allocationItemDBTypes, false, strmangle.SetComplement(allocationItemPrimaryKeyColumns, allocationItemColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, allocationDBTypes, false, strmangle.SetComplement(allocationPrimaryKeyColumns, allocationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, allocationDBTypes, false, strmangle.SetComplement(allocationPrimaryKeyColumns, allocationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Allocation{&b, &c} {
		err = a.SetAllocation(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Allocation != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.AllocationItems[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.AllocationID != x.ID {
			t.Error("foreign key was wrong value", a.AllocationID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.AllocationID))
		reflect.Indirect(reflect.ValueOf(&a.AllocationID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.AllocationID != x.ID {
			t.Error("foreign key was wrong value", a.AllocationID, x.ID)
		}
	}
}
func testAllocationItemToOneSetOpItemUsingItem(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AllocationItem
	var b, c Item

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, allocationItemDBTypes, false, strmangle.SetComplement(allocationItemPrimaryKeyColumns, allocationItemColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, itemDBTypes, false, strmangle.SetComplement(itemPrimaryKeyColumns, itemColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, itemDBTypes, false, strmangle.SetComplement(itemPrimaryKeyColumns, itemColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Item{&b, &c} {
		err = a.SetItem(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Item != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.AllocationItems[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.ItemID != x.ID {
			t.Error("foreign key was wrong value", a.ItemID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ItemID))
		reflect.Indirect(reflect.ValueOf(&a.ItemID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.ItemID != x.ID {
			t.Error("foreign key was wrong value", a.ItemID, x.ID)
		}
	}
}
func testAllocationItemToOneSetOpUnitUsingUnit(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AllocationItem
	var b, c Unit

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, allocationItemDBTypes, false, strmangle.SetComplement(allocationItemPrimaryKeyColumns, allocationItemColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, unitDBTypes, false, strmangle.SetComplement(unitPrimaryKeyColumns, unitColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, unitDBTypes, false, strmangle.SetComplement(unitPrimaryKeyColumns, unitColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Unit{&b, &c} {
		err = a.SetUnit(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Unit != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.AllocationItems[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UnitID != x.ID {
			t.Error("foreign key was wrong value", a.UnitID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UnitID))
		reflect.Indirect(reflect.ValueOf(&a.UnitID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UnitID != x.ID {
			t.Error("foreign key was wrong value", a.UnitID, x.ID)
		}
	}
}

func testAllocationItemsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AllocationItem{}
	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAllocationItemsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AllocationItem{}
	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AllocationItemSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAllocationItemsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AllocationItem{}
	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AllocationItems().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	allocationItemDBTypes = map[string]string{`ID`: `text`, `AllocationID`: `text`, `ItemID`: `text`, `UnitID`: `text`, `Quantity`: `numeric`}
	_                     = bytes.MinRead
)

func testAllocationItemsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(allocationItemPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(allocationItemAllColumns) == len(allocationItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AllocationItem{}
	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AllocationItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAllocationItemsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(allocationItemAllColumns) == len(allocationItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AllocationItem{}
	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AllocationItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, allocationItemDBTypes, true, allocationItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(allocationItemAllColumns, allocationItemPrimaryKeyColumns) {
		fields = allocationItemAllColumns
	} else {
		fields = strmangle.SetComplement(
			allocationItemAllColumns,
			allocationItemPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AllocationItemSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAllocationItemsUpsert(t *testing.T) {
	t.Parallel()

	if len(allocationItemAllColumns) == len(allocationItemPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := AllocationItem{}
	if err = randomize.Struct(seed, &o, allocationItemDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AllocationItem: %s", err)
	}

	count, err := AllocationItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, allocationItemDBTypes, false, allocationItemPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AllocationItem struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AllocationItem: %s", err)
	}

	count, err = AllocationItems().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
