// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AllocationItems string
	Allocations     string
	DonationItems   string
	Donations       string
	Items           string
	RequestItems    string
	Requests        string
	Stocks          string
	Units           string
	Users           string
}{
	AllocationItems: "allocation_items",
	Allocations:     "allocations",
	DonationItems:   "donation_items",
	Donations:       "donations",
	Items:           "items",
	RequestItems:    "request_items",
	Requests:        "requests",
	Stocks:          "stocks",
	Units:           "units",
	Users:           "users",
}
