// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("AllocationItems", testAllocationItemsUpsert)

	t.Run("Allocations", testAllocationsUpsert)

	t.Run("DonationItems", testDonationItemsUpsert)

	t.Run("Donations", testDonationsUpsert)

	t.Run("Items", testItemsUpsert)

	t.Run("PasswordResetRequests", testPasswordResetRequestsUpsert)

	t.Run("RequestItems", testRequestItemsUpsert)

	t.Run("Requests", testRequestsUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Stocks", testStocksUpsert)

	t.Run("Units", testUnitsUpsert)

	t.Run("Users", testUsersUpsert)
}
